name: bookkeepingcode.com
favicon: null
layout_spectrum: 0.8202339059207588
typography_spectrum: 0.6952298916876316
title: Where Canadian Bookkeepers succeed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0593266012147069
  lightness: 0.8421559918206185
  saturation: 0.9416410333942622
  rhythmicContrast: 0.9131103456020355
purpose: []
