name: bookkeepingcode.com
favicon: null
layout_spectrum: 0.25425
typography_spectrum: 0.6952298916876316
title: Where Canadian Bookkeepers succeed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0000'
    - '#e3d9bf'
    - '#a28c65'
    - '#624729'
    - '#d1c3a4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
